question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
]
question_data1 = [{"type": "boolean",
                   "difficulty": "easy",
                   "category": "Science: Mathematics",
                   "question": "An equilateral triangle always has every angle measuring 60&deg;.",
                   "correct_answer": "True",
                   "incorrect_answers": ["False"]},
                  {"type": "boolean",
                   "difficulty": "easy",
                   "category": "Entertainment: Japanese Anime &amp; Manga",
                   "question": "The name of the attack &quot;Kamehameha&quot; in Dragon Ball Z was named after a famous king of Hawaii.",
                   "correct_answer": "True",
                   "incorrect_answers": ["False"]},
                  {"type": "boolean",
                   "difficulty": "easy",
                   "category": "Entertainment: Video Games",
                   "question": "Tetris is the #1 best-selling video game of all-time.",
                   "correct_answer": "False",
                   "incorrect_answers": ["True"]},
                  {"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
                   "question": "Not including false teeth; A human has two sets of teeth in their lifetime.",
                   "correct_answer": "True", "incorrect_answers": ["False"]},
                  {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                   "question": "There are 2 player roles in Trouble in Terrorist Town.",
                   "correct_answer": "False", "incorrect_answers": ["True"]},
                  {"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
                   "question": "An atom contains a nucleus.", "correct_answer": "True",
                   "incorrect_answers": ["False"]},
                  {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Books",
                   "question": "&quot;Elementary, my dear Watson&quot; is a phrase that is never truly said within the Conan Doyle books of Sherlock Holmes.",
                   "correct_answer": "True", "incorrect_answers": ["False"]},
                  {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                   "question": "A scientific study on peanuts in bars found traces of over 100 unique specimens of urine.",
                   "correct_answer": "False", "incorrect_answers": ["True"]},
                  {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
                   "question": "Brandon Routh plays the titular character in the movie &quot;John Wick&quot;.",
                   "correct_answer": "False", "incorrect_answers": ["True"]},
                  {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                   "question": "Gumbo is a stew that originated in Louisiana.",
                   "correct_answer": "True", "incorrect_answers": ["False"]}
                  ]
